AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table for user responses'

Resources:
  UserResponsesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: phonitale-user-responses
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: UserRoundIndex
          KeySchema:
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Project
          Value: Phonitale
        - Key: Environment
          Value: Production 